// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3RoxpmZCCYmjUf4_2kgsYMqMD0WtejRc',
    appId: '1:340724092441:android:4ffcc69d6ede2228422488',
    messagingSenderId: '340724092441',
    projectId: 'jal-hr-a55dc',
    databaseURL: 'https://jal-hr-a55dc-default-rtdb.firebaseio.com',
    storageBucket: 'jal-hr-a55dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB32ZlHyjCk0GF7dD_XkM_DbfdUzDo8vcc',
    appId: '1:340724092441:ios:dc52d5b5506a8791422488',
    messagingSenderId: '340724092441',
    projectId: 'jal-hr-a55dc',
    databaseURL: 'https://jal-hr-a55dc-default-rtdb.firebaseio.com',
    storageBucket: 'jal-hr-a55dc.firebasestorage.app',
    iosBundleId: 'com.jahr.sahala',
  );
}
